### ISSUE TITLE
l4d2_getup_fixes

### ISSUE THREAD

**Issue by umlka** [Target5150/MoYu_Server_Stupid_Plugins#14]
L 02/14/2022 - 07:14:48: [SM] Exception reported: Client 9 is not connected
L 02/14/2022 - 07:14:48: [SM] Blaming: l4d2_getup_fixes.smx
L 02/14/2022 - 07:14:48: [SM] Call stack trace:
L 02/14/2022 - 07:14:48: [SM]   [0] GetClientUserId
L 02/14/2022 - 07:14:48: [SM]   [1] Line 224, d:\Sourcemod\scripting\l4d2_getup_fixes.sp::Event_ChargeEnd

**Comment by jensewe** [comment]
Thanks for testing and reports! I've committed a fix to this, would like to wait for your favorable reply.
感谢测试和反馈！如果不介意的话希望能再尝试一下刚发布的修复版 👍
