### ISSUE TITLE
友伤显示插件bug

### ISSUE THREAD

**Issue by apples1949** [Target5150/MoYu_Server_Stupid_Plugins#17]
zm 自己编译的插件
别人攻击你 显示的是你自己攻击自己
其他没问题

**Comment by jensewe** [comment]
应该ok了 感谢反馈.

**Comment by apples1949** [comment]
![QQ截图20220508155949](https://user-images.githubusercontent.com/49244656/167544512-d2340896-d998-4390-a594-d67c7ee29c0b.png)
![QQ截图20220508160107](https://user-images.githubusercontent.com/49244656/167544522-eca046d4-8fce-408f-a575-524c8775b3f2.png)
![QQ截图20220508155140](https://user-images.githubusercontent.com/49244656/167544525-b647fcd2-964a-4f23-b3d5-893a9d3beb54.png)
![QQ截图20220508155732](https://user-images.githubusercontent.com/49244656/167544530-f18b75f0-5a5c-43c5-908b-7fb18ef4e68e.png)
旁观显示伤害会出现英文文本 目前没有报告正常游玩显示问题

**Comment by jensewe** [comment]
感谢反馈，如果有时间的话希望能试一试PR里的版本，我一个人不好测。

**Comment by apples1949** [comment]
多人战役出现的报错 
L 05/19/2022 - 00:00:08: [SM] Exception reported: Translation failed: invalid client index -1 (arg 6)
L 05/19/2022 - 00:00:08: [SM] Blaming: [addons]l4d_ffannounce.smx
L 05/19/2022 - 00:00:08: [SM] Call stack trace:
L 05/19/2022 - 00:00:08: [SM]   [0] FormatEx
L 05/19/2022 - 00:00:08: [SM]   [1] Line 241, C:\Users\apples1949\Desktop\l4dplugins\1.11\l4d_ffannounce.sp::AnnounceFF
对抗目前无任何问题 可以无视了（

**Comment by jensewe** [comment]
🤔很奇怪的报错，如果你的translation设置没问题的话，设计上的局限导致这插件目前只能手动添加4人以上的语句设置。
