### ISSUE TITLE
smoker catch saferoom player

### ISSUE THREAD

**Issue by ProjectSky** [Target5150/MoYu_Server_Stupid_Plugins#19]
* vanilla
![vanilla](https://user-images.githubusercontent.com/16351827/169692807-ae5129d9-06c1-4f69-aab6-25c6f9b0f2d4.gif)

* load l4d_tongue_bend_fix
![bend_fix](https://user-images.githubusercontent.com/16351827/169692827-a5d937a9-9f52-4f28-9c5c-b10db763d0ef.gif)
 
as shown vanilla version will auto break tongue, l4d_tongue_bend_fix break this rule

**Comment by jensewe** [comment]
Good find👍
I've made a PR to fix this one, and roughly went through tests and seemed to avoid this case. It would be appreciated if you could help confirm on this.

**Comment by ProjectSky** [comment]
quick fix👍 i will test it.
