### ISSUE TITLE
readyup plugin disable?????

### ISSUE THREAD

**Issue by CanadianJeff** [Target5150/MoYu_Server_Stupid_Plugins#2]
kinda curious why I cant have this plugin loaded but disabled for public matches?

`l4d_ready_enable 0` does nothing as it says

**Comment by jensewe** [comment]
Modified version here uses this convar only to switch modes between manual ready and auto start.

Ready Up doesn't come with the functionality of self-disabling. The following are codes from original version: 
`CreateConVar("l4d_ready_enabled", "1", "This cvar doesn't do anything, but if it is 0 the logger wont log this game.", 0, true, 0.0, true, 1.0);`

Given this is a plugin built for confogl that manages a lot of configurations, actually I don't think it matters whether a plugin can disable itself. And if it can, there would probably be issues from other plugins that respect ready up state.

By the way, I developed the auto-start mode to meet my folk's need, who hold servers dedicated for lobby connect games. Perhaps it can fit your need.

**Comment by jensewe** [comment]
No further reply, assuming resolved.
