### ISSUE TITLE
Double get up  plugin cause animation bug in this case

### ISSUE THREAD

**Issue by lunatixxx** [Target5150/MoYu_Server_Stupid_Plugins#24]
As a tank if you punch a downed survivor, it will launch the animation where he stands up (happen everytime). This bug only occur when i have this plugin, already reported a long time ago but being ignored https://github.com/SirPlease/L4D2-Competitive-Rework/issues/81

https://ibb.co/y6wgJF4

**Comment by jensewe** [comment]
I believe I have not seen this case even before my solution for get-up as long as setup with pure competitive rework, only noticed this in some coop servers.
Well I don't think I could remember under what setup it could happen. Figuring out where issue lies would be a good experience, but given those get-up handlers are gone, let's just leave it be.

**Comment by lunatixxx** [comment]
I do use almost everything of competitive rework, but maybe i missed a plugin or a cvar. Could it have more animations problems like this one?

**Comment by jensewe** [comment]
The basic ones working for get-ups were `double_getup` and `l4d2_getupfix`, and later `l4d2_charger_getup_fix` was added for not godframed charge get-ups.
I would say yes as for more animation issues, those ones are all working with timers and animation being played, provided with unreliable information. But guess they aren't quite related with the case you described, I would believe that more like `GhostTank` module of confoglcompmod raises it.
Anyway, unreliable handlers are gone, as we should no longer suffer from inconsistent get-ups.
