### ISSUE TITLE
l4d2 pickup plugins bug

### ISSUE THREAD

**Issue by fantasylidong** [Target5150/MoYu_Server_Stupid_Plugins#26]
1、已经是双枪状态时拾取近战，会显示为小手枪，但是实际在slots1位置，功能影响为刚切换时无法开枪，[演示视频](https://youtu.be/xkBv1Cy789U)
2、有第一把小手枪的情况，用give命令给的第二把小手枪依旧会切换到slots2，[演示视频](https://youtu.be/y0xa6nD0lgc)
这个不知道可不可以实现，拾取第二把情况是正常的

**Comment by jensewe** [comment]
> 1、已经是双枪状态时拾取近战，会显示为小手枪，但是实际在slots1位置，功能影响为刚切换时无法开枪，[演示视频]

开始弄出来的时候就发现了。不清楚有没有办法，就像你所看到的是一个视觉效果问题，而这问题比较可能是客户端预测导致的。

**Comment by jensewe** [comment]
我PR了一个修复，如果可以的话还请试试。目前自己试了一下，还没有你所描述的问题。

**Comment by fantasylidong** [comment]
Nice work!
测试了一下，全部没问题了，十分谢谢！
