### ISSUE TITLE
readyup bug

### ISSUE THREAD

**Issue by PaaNChaN** [Target5150/MoYu_Server_Stupid_Plugins#28]
hello :)

im using the latest version of readyup.
using the "Climb Everywhere" plugin causes the survivors to freeze.
Also, idk if this plugin is affecting it, but it is forcing me to return to the saferoom.

i have taken a video so check it out.
https://www.youtube.com/watch?v=ugBOtPwtRNs

**Comment by jensewe** [comment]
https://forums.alliedmods.net/showthread.php?p=1504248
Do you use this one? As far this one cannot be reproduced on my end, not even the stuck on the fence.

**Comment by PaaNChaN** [comment]
> Do you use this one? As far this one cannot be reproduced on my end, not even the stuck on the fence.

sorry.
the problem with the survivors freezing was caused by a plugin i have customized.

also, the problem of survivors being returned to the saferoom wasnt resolved.
after about 1.2 minutes, the survivors is forced return the saferoom.

https://www.youtube.com/watch?v=zVXg_DW_3lE

**Comment by jensewe** [comment]
https://github.com/Target5150/MoYu_Server_Stupid_Plugins/blob/c9a137106112d16235fb87133eb12ecfd8dca01b/The%20Last%20Stand/readyup/readyup/game.inc#L41

You might want to make sure this function locates in `InitiateReadyUp()` or like, in this case it is called by a timer.

**Comment by jensewe** [comment]
Sincere apology for my carelessness, this should be fixed in the last update.
