### ISSUE TITLE
sweep_patch

### ISSUE THREAD

**Issue by vikingo12** [Target5150/MoYu_Server_Stupid_Plugins#3]
[SM] Blaming: l4d_sweep_fist_patch.smx
[SM] Call stack trace:
[SM]   [0] CreateEntityByName
[SM]   [1] Line 172, J:\Documents\GitHub\MoYu_Server_Stupid_Plugins\The Last Stand\l4d_sweep_fist_patch\l4d_sweep_fist_patch.sp::IsAllowedGamemode
[SM]  [2] Line 111, J:\Documents\GitHub\MoYu_Server_Stupid_Plugins\The Last Stand\l4d_sweep_fist_patch\l4d_sweep_fist_patch.sp::OnConfigsExecuted
 [SM]   [3] Line 119, J:\Documents\GitHub\MoYu_Server_Stupid_Plugins\The Last Stand\l4d_sweep_fist_patch\l4d_sweep_fist_patch.sp::OnGameModeChanged

**Comment by jensewe** [comment]
Could you please specify any possible way to reproduce this?
And it would be appreciated if you could provide a previous line as well, which should be like:
> L 06/08/2021 - 19:43:57: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)

**Comment by vikingo12** [comment]
I couldn't find that line, FULL LOG:
L 06/16/2021 - 01:42:50: [SM] Blaming: l4d_sweep_fist_patch.smx
L 06/16/2021 - 01:42:50: [SM] Call stack trace:
L 06/16/2021 - 01:42:50: [SM]   [0] CreateEntityByName
L 06/16/2021 - 01:42:50: [SM]   [1] Line 172, J:\Documents\GitHub\MoYu_Server_Stupid_Plugins\The Last Stand\l4d_sweep_fist_patch\l4d_sweep_fist_patch.sp::IsAllowedGamemode
L 06/16/2021 - 01:42:50: [SM]   [2] Line 111, J:\Documents\GitHub\MoYu_Server_Stupid_Plugins\The Last Stand\l4d_sweep_fist_patch\l4d_sweep_fist_patch.sp::OnConfigsExecuted
L 06/16/2021 - 01:42:50: [SM]   [3] Line 119, J:\Documents\GitHub\MoYu_Server_Stupid_Plugins\The Last Stand\l4d_sweep_fist_patch\l4d_sweep_fist_patch.sp::OnGameModeChanged
L 06/16/2021 - 01:42:51: Error log file session closed.

**Comment by vikingo12** [comment]
I think I got it, It happened because I switched to versus using this plugin
