### ISSUE TITLE
Readyup rare bug with round start event

### ISSUE THREAD

**Issue by lunatixxx** [Target5150/MoYu_Server_Stupid_Plugins#30]
Basically even after the countdown and going out of the safe area you will still hear the music from the intro and natural hordes will never spawn, only saw it happened on intro maps for now.

**Comment by jensewe** [comment]
I cannot confirm this actually exists at least the intro music always goes off whenever trying to leaving start area, in ready up or not.
As for natural hordes, if the interval values are set within reasonable range, version before https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/d0b58109a5a4ac9aa3a75519178f7bf73851481d won't bother with mob countdown anyway.

**Comment by lunatixxx** [comment]
I'm not using intro cutscene skip if that matters.

**Comment by jensewe** [comment]
I'm afraid it's not related, the plugin should do the same process as the game, but only earlier.
Tried it myself, it didn't seem to have any difference as the mob spawns normally.
Worth mentioning, the intro music looks actually bugged out keeping playing if spectate and rejoin after leaving saferoom once during ready up. Anyway it's kinda out of the plugin's scope so probably no fix for it, instead Valve's fault :)
