### ISSUE TITLE
Bot glitched because of readyup?

### ISSUE THREAD

**Issue by lunatixxx** [Target5150/MoYu_Server_Stupid_Plugins#34]
Occasionnally we have a bot that refuse to move or disappear with a weird name "k9c....", sm_fixbots does not help.

**Comment by jensewe** [comment]
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/68f23c217c1d6eeb8f445c6c3de06a10f1d53f76/addons/sourcemod/scripting/playermanagement.sp#L504

Might consider a rework sooner or later.
Close for being irrelavant with here.
