### ISSUE TITLE
l4d2_charge_target_fix和 l4d2_getup_fixes pve模式问题

### ISSUE THREAD

**Issue by fantasylidong** [Target5150/MoYu_Server_Stupid_Plugins#37]
l4d2_charge_target_fix:
这个插件因为我把动画速率播放改成了1000（SetEntPropFloat(client, Prop_Send, "m_flCycle", 1000.0, 0); 而且也不一定是这个原因），然后被牛撞之后就会触发无法被牛，猴子，ht控制，舌头可以拉 (视频：https://file.trygek.com/record/test1.mp4 ）

l4d2_getup_fixes:
把gfc_long_charger_duration 值从3.1改为2.8后，有时会触发双起身，（视频： https://file.trygek.com/record/test2.mp4    这个视频并没有改动画播放速率，触发了双起身之后，然后也不能被控制了）

PS：第一个视频牛被1v1插件处死了，第二个也是，是不是因为这个问题？

**Comment by jensewe** [comment]
视频链接403 Forbidden了

> l4d2_charge_target_fix: 这个插件因为我把动画速率播放改成了1000（SetEntPropFloat(client, Prop_Send, "m_flCycle", 1000.0, 0); 而且也不一定是这个原因），然后被牛撞之后就会触发无法被牛，猴子，ht控制，舌头可以拉 (视频：[https://file.trygek.com/record/Left%204%20Dead%202%202023.01.13%20-%2019.20.42.03.mp4）](https://file.trygek.com/record/Left%204%20Dead%202%202023.01.13%20-%2019.20.42.03.mp4%EF%BC%89)

你可能需要设置 z_charge_pinned_collision 2或者3

**Comment by fantasylidong** [comment]
测试后我上面情况暂时没问题，明天放服务器组里复杂测试一下还有没有其他情况导致这个问题

**Comment by fantasylidong** [comment]
> 视频链接403 Forbidden了
> 
> > l4d2_charge_target_fix: 这个插件因为我把动画速率播放改成了1000（SetEntPropFloat(client, Prop_Send, "m_flCycle", 1000.0, 0); 而且也不一定是这个原因），然后被牛撞之后就会触发无法被牛，猴子，ht控制，舌头可以拉 (视频：[https://file.trygek.com/record/Left%204%20Dead%202%202023.01.13%20-%2019.20.42.03.mp4）](https://file.trygek.com/record/Left%204%20Dead%202%202023.01.13%20-%2019.20.42.03.mp4%EF%BC%89)
> 
> 你可能需要设置 z_charge_pinned_collision 2或者3

新pr后还需要改这个值吗，这个值我看SirPlease项目里的默认值好像是1，因为我没有在confogl里进行设置

**Comment by jensewe** [comment]
PR过去的时候还没有更新到这https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/11d608892b22386bff1ee6434d97c63f5cd4c6ab 那边还是一个单开关控制两个碰撞判定

**Comment by fantasylidong** [comment]
没问题了👌
谢谢
