### ISSUE TITLE
Memory leaking in l4d_tank_damage_announce

### ISSUE THREAD

**Issue by nikita1824** [Target5150/MoYu_Server_Stupid_Plugins#40]
Hello, recently found that you don't close DataPack that you cast [here](https://github.com/Target5150/MoYu_Server_Stupid_Plugins/blob/master/The%20Last%20Stand/l4d_tank_damage_announce/l4d_tank_damage_announce.sp#L372). 

I hope it was helpful.
Thanks a lot for updates which you do.

**Comment by jensewe** [comment]
A pleasure if anyone enjoys these works. Thanks for reporting!
