### ISSUE TITLE
l4d_fix_deathfall_cam.txt is not found

### ISSUE THREAD

**Issue by Kaze1027** [Target5150/MoYu_Server_Stupid_Plugins#41]
Put the l4d_fix_deathfall_cam.txt to your gamedata folder.

But there is no file named l4d_fix_deathfall_cam.txt.

**Comment by jensewe** [comment]
Yes because the extra info from gamedata is no longer needed after I found the native way to do this.
I'm quite lazy at updating the readmes but trying my best to keep these plugins good to go, so just what you see is what you get :)

**Comment by Kaze1027** [comment]
Thx, I guess so, and I put it into my server, it works well, a good plugin!
