### ISSUE TITLE
Bug in l4d_tongue_block_fix

### ISSUE THREAD

**Issue by nikita1824** [Target5150/MoYu_Server_Stupid_Plugins#42]
Hello, installing l4d_tongue_block_fix plugin causes ai's smoker ability to be broken (smoker bots can't grab any survivor at all).
I tried to filter bots in CH_PassFilter() to avoid plugin to interrupt in ai's ability behavior but it didn't help. Do you have any idea how to solve this problem?

**Comment by jensewe** [comment]
Not really remember there's difference in tongue chasing between bots and humans. And I cannot reproduce that one on my end.
Would you like to share some footages, and if possible, double check with all other plugins unloaded?

**Comment by nikita1824** [comment]
yeap, I'm not sure about other plugins
here is video link: https://youtu.be/sy7g-fYeSp4

**Comment by jensewe** [comment]
If you don't mind, check out the following debug code and try again to see if there's anything strange?

```sourcepawn
	static int lastHit = -1;
	if (lastHit != touch)
	{
		lastHit = touch;
		
		static char cls[64];
		if (pass > MaxClients)
		{
			if (!GetEdictClassname(pass, cls, sizeof(cls)))
				return Plugin_Continue;
			
			if (strcmp(cls, "ability_tongue") != 0)
				return Plugin_Continue;
			
			if (touch > 0 && touch <= MaxClients)
			{
				if (!GetClientName(touch, cls, sizeof(cls)))
					return Plugin_Continue;
			}
			else if (!GetEdictClassname(touch, cls, sizeof(cls)))
				return Plugin_Continue;
			
			PrintToChatAll("[DEBUG] Tongue fly collision: %s", cls);
		}
	}
```

**Comment by nikita1824** [comment]
Hello, I'm sorry for the late reply.
Pattern of the bug has changed with version 1.3 of the plugin.
I don't know how to explain it. Here is the video link: https://youtu.be/K1sEax-2lqI
From debug messages it's hard to tell what's wrong...

**Comment by jensewe** [comment]
Pushed a fix via pull request, tested and it's fine on my end.
Appreciate if you could help confirm :)

**Comment by nikita1824** [comment]
Yeap, now it works fine, thanks a lot for the fix.
