### ISSUE TITLE
Plugin timer and pause

### ISSUE THREAD

**Issue by lunatixxx** [Target5150/MoYu_Server_Stupid_Plugins#48]
Is it possible to order a plugin timer to ignore a pause? Because currently the pause stop all timers.

**Comment by jensewe** [comment]
I think you're wondering about any other timer than SM's one but actually SM timer proceeds regardless of pauses. In fact the pause plugin uses SM timers to refresh panels.

**Comment by jensewe** [comment]
Perhaps the author suspends the afk check during a pause. The timer can definitely keep onto ticking.
