### ISSUE TITLE
[L4D2] Vomit trace patch (Memory patch error)

### ISSUE THREAD

**Issue by BRU7U5** [Target5150/MoYu_Server_Stupid_Plugins#49]
L 06/23/2023 - 20:16:01: [SM] Exception reported: Invalid patch name ShouldHitEntity_MyInfectedPointer
L 06/23/2023 - 20:16:01: [SM] Blaming: patches/l4d_vomit_trace_patch.smx
L 06/23/2023 - 20:16:01: [SM] Call stack trace:
L 06/23/2023 - 20:16:01: [SM]   [0] MemoryPatch.CreateFromConf
L 06/23/2023 - 20:16:01: [SM]   [1] Line 34, J:\Documents\GitHub\MoYu_Server_Stupid_Plugins\The Last Stand\l4d_vomit_trace_patch\l4d_vomit_trace_patch.sp::OnPluginStart

**Comment by jensewe** [comment]
Unfortunately this is only for use in L4D1, as there're no such issues in L4D2.

**Comment by BRU7U5** [comment]
Alright, thank you!
