### ISSUE TITLE
Do you have some cool ideas?

### ISSUE THREAD

**Issue by cy115** [Target5150/MoYu_Server_Stupid_Plugins#51]
I`m much appreciated for your hard working on readyup plugin
Would you like to do the same on coop mode?
The same panel, same ready&unready status, same god mode and always teleport survivor to safe area when they left it before round is live
i used to browser your code but it is a large work to make it....So please bring us a readyup plugin for coop mode!

**Comment by cy115** [comment]
> 不, 你只是想**白嫖**

挨透

**Comment by fbef0102** [comment]
https://github.com/fbef0102/Game-Private_Plugin/tree/main/Plugin_%E6%8F%92%E4%BB%B6/Server_%E4%BC%BA%E6%9C%8D%E5%99%A8/readyup
