### ISSUE TITLE
Readyup question (Revised)

### ISSUE THREAD

**Issue by JKYuKicyan** [Target5150/MoYu_Server_Stupid_Plugins#63]
After the countdown is over, will be randomly refreshed some common zombie.
I only modified customizable content among them "panel.inc"and"sound.inc"
And there were no errorslog for "readyup.smx"
When I use ZoneMod 2.8.7 something similar has happened (unmodified)
Now when I use unmodified smx, the issue is solved (ZoneMod 2.8.9)
I can provide the video file if needed
Sys:Ubuntu 22.04.3 L4D2 Dedicated Server
The above text uses a translator, please understand if it cannot be expressed smoothly

**Comment by jensewe** [comment]
不太清楚“刷新小怪”是指什么
可以的话提供视频吧

**Comment by JKYuKicyan** [comment]
> 不太清楚"刷新小怪"是指什么 可以的话提供视频吧

Like this.
https://1drv.ms/v/s!AmtmL_zp0lxOnWZdKZ7CgJ4Gulwt?e=Kw666p
Whether it's any map, round, or level
I'm curious why it doesn't output an error log, or is it a system-level bug?

**Comment by jensewe** [comment]
试试 https://github.com/Target5150/MoYu_Server_Stupid_Plugins/pull/64 ？
我不太能确定具体原因，但这个方法很有问题。

**Comment by JKYuKicyan** [comment]
> 试试 #64 ？ 我不太能确定具体原因，但这个方法很有问题。

Exactly, Problem solved, thank you so much, I'll do more testing in the future.
: )
