### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by SmeraldoTAT** [Target5150/MoYu_Server_Stupid_Plugins#66]
// D:\Steam\steamapps\common\Left 4 Dead 2\left4dead2\addons\sourcemod\scripting\include\left4dhooks_silver.inc(961) : error 017: undefined symbol "PlayerAnimState"
//
// 1 Error.
//
// Compilation Time: 0.48 sec

**Comment by SmeraldoTAT** [comment]
l4d_fix_common_shove.sp

**Comment by jensewe** [comment]
Update left4dhooks.
https://forums.alliedmods.net/showthread.php?t=321696

**Comment by jensewe** [comment]
`#tryinclude <left4dhooks_silver>` 
Try removing/commenting out this line in `left4dhooks_anim.inc` before compile.

**Comment by SmeraldoTAT** [comment]
> `#tryinclude <left4dhooks_silver>` 在编译之前尝试删除/注释掉此行。`left4dhooks_anim.inc`

this plugin is for l4d1 or l4d2?

**Comment by jensewe** [comment]
Of couese as you can check the title in README file.
