### ISSUE TITLE
l4d_fix_linux_surface.smx会报错

### ISSUE THREAD

**Issue by VenusPark** [Target5150/MoYu_Server_Stupid_Plugins#67]
ExpandPatchFile: Failed to import VMT file，它也没指出需要什么vmt
![PixPin_2024-04-30_18-25-58](https://github.com/Target5150/MoYu_Server_Stupid_Plugins/assets/79137449/452dfe35-31d2-4386-a03c-147ee780bf02)

**Comment by jensewe** [comment]
加了路径提示和路径修复，还没想过这一步真会失败。方便的话请说下地图名字。

**Comment by VenusPark** [comment]
> 加了路径提示和路径修复，还没想过这一步真会失败。方便的话请说下地图名字。
忧郁3的M1

**Comment by jensewe** [comment]
`glubtastic3_1`
是这张图吗？这边看了并没有问题。
也许是系统问题，看看什么系统，更新一下插件再试试。

**Comment by VenusPark** [comment]
貌似知道它为什么会报错了，因为服务端不需要材质和音效，也为了节省云服务器三方占用，我上传的图都是去掉了材质和音效的，插件应该是无法读取对应的vmt才报错了...估计这个没办法解决，似了😭
![QQ图片20240501204723](https://github.com/Target5150/MoYu_Server_Stupid_Plugins/assets/79137449/26afb218-8dad-4f7b-b571-bdec5c99f741)
