### ISSUE TITLE
[L4D & 2] Fix Stagger Direction v1.1 overwrites shover's index in L4D_OnShovedBySurvivor() forward in left4dhooks

### ISSUE THREAD

**Issue by nikita1824** [Target5150/MoYu_Server_Stupid_Plugins#70]
This causes some problems with plugins like: [L4D2 Tank & Charger M2 Fix](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/55bf7783ad22df54bc46f9fdf232fb08353afabc/addons/sourcemod/scripting/l4d2_tank_charger_m2_fix.sp#L17), [L4D2 No Hunter Deadstops v3.4](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/55bf7783ad22df54bc46f9fdf232fb08353afabc/addons/sourcemod/scripting/l4d2_no_hunter_deadstops.sp#L22), [L4D2 No Post-Jockeyed Shoves](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/55bf7783ad22df54bc46f9fdf232fb08353afabc/addons/sourcemod/scripting/l4d2_no_post_jockey_deadstops.sp#L15), [[L4D2] No Hunter Deadstops v1.0.3](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/55bf7783ad22df54bc46f9fdf232fb08353afabc/addons/sourcemod/scripting/l4d2_hunter_no_deadstops.sp#L38), [etc](https://github.com/search?q=repo%3ASirPlease%2FL4D2-Competitive-Rework%20L4D_OnShovedBySurvivor&type=code)

**Comment by jensewe** [comment]
Looks like a DHooks-end issue, it doesn't check for difference in setup.
https://github.com/alliedmodders/sourcemod/blob/f086c0a63861230cabe1fff7bfa8a36d7e2ffc77/extensions/dhooks/DynamicHooks/manager.cpp#L85

Consider a workaround by bringing L4DHooks forwards back at the moment.
